name = "TicTacToe"
uuid = "1f9fd063-3fba-4927-8545-bdfdef78b5e5"
authors = ["Bernhard König <github@diro.ch> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
